version: '3.7'

services:
  star-wars-search:
    container_name: star-wars-search
    restart: unless-stopped
    image: ghcr.io/deantawonezvi/star-wars-search:${BRANCH}-${APP_VERSION}
    networks:
      - proxy
    labels:
      ##Set the lowest routing priority == 1
      ##This will solve the overlap with api routes
      ##- traefik.http.routers.star-wars-search.priority=1
      ##HTTPS
      - "traefik.http.routers.star-wars-search.entrypoints=websecure"
      - "traefik.http.routers.star-wars-search.rule=Host(`star-wars-search.deant.work`)"
      - "traefik.http.middlewares.star-wars-search-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.star-wars-search-secure.entrypoints=websecure"
      - "traefik.http.routers.star-wars-search-secure.rule=Host(`star-wars-search.deant.work`)"
      - "traefik.http.routers.star-wars-search-secure.tls=true"
      - "traefik.http.routers.star-wars-search-secure.tls.certresolver=http"
    env_file:
      - .env

networks:
  proxy:
    external: true
